# -*- coding: utf-8 -*-
"""Per-case config + bilingual prose for the 10 test cases."""

# scenes: list of (start, end) per type; ann: (track, t0, t1, zh, en); zoom: (t0, t1)
CASES = {
 1: dict(
   dur=36.76, cmd="--echo 0:10 --near 10:26 --dt 26:36",
   scenes=dict(echo=[(0,10)], near=[(10,26)], dt=[(26,36)]),
   zoom=(0,10),
   ann=[("b1",4,7,"试听：偶发微弱残余（4–7s）","Audible faint residual (4-7s)"),
        ("b1",34,35.5,"试听：微弱残余（34–35.5s）","Audible faint residual (34-35.5s)")],
   prov_zh="实录测试素材，约 36.8 秒。", prov_en="Recorded test clip, ~36.8 s.",
   title_zh="回声 / 近端 / 双讲全场景对比", title_en="Full-scenario comparison: echo / near-end / double-talk",
   subj_zh=["**B1**：回声段第 4–7 秒偶尔可以听到很小的残余回声；双讲段第 34–35.5 秒也能听到很小的残余回声；",
            "**A1、A2、B2**：全程试听未发现可察觉的残余回声或语音损伤。"],
   subj_en=["**B1**: faint residual echo occasionally audible at 4-7 s in the echo segment, and again at 34-35.5 s in double-talk;",
            "**A1, A2, B2**: no perceivable residual echo or speech damage anywhere."],
   verdict_zh=["主客观互相印证：B1 的可闻残余对应其 FE-ST Echo 仅 2.78 分（四者中唯一跌出 3.8 分档）、ERLE 最低（19.7 dB）、残余最高（−48.9 dBFS）；双讲瞬时残余对应 DT Echo 4.27 为四者最低。A2 主观全程无回声，与 −72.4 dBFS（听阈之下）吻合。",
              "**判定：A1 对 B1 —— A1 胜**，算力节省 54% 的同时主客观全面领先。**A2 对 B2 —— 各有胜场**：A2 在算力、抑制深度、总内存领先；B2 的 AECMOS 分项略高 0.1–0.2 分、延迟少 32 ms，主观两者均无可察觉问题。"],
   verdict_en=["Subjective and objective agree: B1's audible residual matches its FE-ST Echo of only 2.78 (the only config below the 3.8 tier), the lowest ERLE (19.7 dB) and the highest residual (-48.9 dBFS); its transient double-talk residual matches the lowest DT Echo (4.27). A2 being subjectively echo-free matches -72.4 dBFS, below audibility.",
              "**Verdict: A1 vs B1 - A1 wins**, leading across the board while saving 54% compute. **A2 vs B2 - split decision**: A2 leads on compute, suppression depth and total memory; B2 scores 0.1-0.2 higher on AECMOS sub-metrics with 32 ms less delay; subjectively both are clean."],
 ),
 2: dict(
   dur=40.0, cmd="--echo 6:8,26:40 --near 0:6.3 --dt 8:24.6",
   scenes=dict(echo=[(6,8),(26,40)], near=[(0,6.3)], dt=[(8,24.6)]),
   zoom=(5.5,9),
   ann=[("b1",6.4,6.7,"试听：明显残余（收敛慢）","Audible clear residual (slow convergence)"),
        ("b1",8,24.6,"双讲段可闻残余（较 A1 更显著）","Audible DT residual (more prominent than A1)"),
        ("a1",8,24.6,"双讲段可闻轻微残余","Faint audible DT residual")],
   prov_zh="实录测试素材，约 40 秒的长样本；开头为近端单讲，中段为长双讲，后段为回声。",
   prov_en="Recorded ~40 s long clip: near-end single-talk first, a long double-talk middle, echo at the end.",
   title_zh="长双讲样本：收敛速度与双讲残余对比", title_en="Long double-talk clip: convergence speed and DT residual",
   subj_zh=["**B1**：第 6.4–6.7 秒残留非常明显的回声，波形上清晰可见——该段处于回声段开头，说明 B1 的收敛速度远慢于 A1；",
            "**A1、A2**：该段无可闻残余；**B2** 借 AI 降噪基本消除了这段残余，但仍有一点点；",
            "**双讲段（8–24.6 秒）**：A1 与 B1 都能听到残余回声，但 B1 的残余明显比 A1 更显著。"],
   subj_en=["**B1**: very clear residual echo at 6.4-6.7 s, plainly visible in the waveform - this sits at the start of an echo segment, showing B1 converges far more slowly than A1;",
            "**A1, A2**: no audible residual there; **B2**'s AI denoiser mostly removes it, though a trace remains;",
            "**Double-talk (8-24.6 s)**: residual echo is audible in both A1 and B1, but B1's is clearly more prominent."],
   verdict_zh=["客观数据与听感严丝合缝：B1 是唯一 FE-ST Echo 跌破 4 分的配置（3.28），ERLE 也最低（12.3 dB）；双讲残余更显著对应 DT Echo 3.65 对 A1 的 4.50。值得注意本例近端含噪较重（四者 NE-ST Other 均低），A2 的激进降噪把近端自然度压到了 1.91。",
              "**判定：A1 对 B1 —— A1 全项胜**（成对比较 17 项质量指标全部 win:A1）。**A2 对 B2 —— B2 质量占优、A2 算力占优**：B2 在 ERLE、近端自然度和综合分上领先，A2 以 48% 的算力节省换取；对近端噪声重的场景，A1 或 B2 是更稳妥的档位。"],
   verdict_en=["The numbers match the ears exactly: B1 is the only config whose FE-ST Echo falls below 4 (3.28) with the lowest ERLE (12.3 dB); its more prominent DT residual maps to DT Echo 3.65 vs A1's 4.50. Note the near end is noisy in this clip (all four NE-ST Other scores are low), and A2's aggressive denoising pushes near-end naturalness down to 1.91.",
              "**Verdict: A1 vs B1 - A1 wins every row** (all 17 quality rows in the paired comparison read win:A1). **A2 vs B2 - B2 on quality, A2 on compute**: B2 leads ERLE, near-end naturalness and the composite, which A2 trades for a 48% compute saving; for noisy near-end scenarios A1 or B2 are the safer tiers."],
 ),
 3: dict(
   dur=11.18, cmd="--echo 0.93:1.8,7.35:8 --near 6.85:7.33,9.39:10.45,11.25:12.1 --dt 1.76:6.84,8:9.38,10.45:11.18",
   scenes=dict(echo=[(0.93,1.8),(7.35,8)], near=[(6.85,7.33),(9.39,10.45)], dt=[(1.76,6.84),(8,9.38),(10.45,11.18)]),
   zoom=(0.6,2.2),
   ann=[("b1",0.97,1.6,"回声被放大（负 ERLE）","Echo amplified (negative ERLE)"),
        ("b2",0.97,1.6,"AI 降噪仍未消除","AI NS still fails to remove it")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `fbkhafa8n0W-W8ytgzClpg_doubletalk_with_movement` 的 `_mic.wav` 与 `_lpb.wav`（带走动的双讲样本）。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `fbkhafa8n0W-W8ytgzClpg_doubletalk_with_movement` (double-talk with movement).",
   title_zh="走动双讲样本：基线出现回声放大（负 ERLE）", title_en="Double-talk with movement: baseline amplifies the echo (negative ERLE)",
   subj_zh=["整体而言四个配置在本样本上的效果都不算理想；",
            "**B1**：不但没有消除回声，反而把回声**放大**了——看 0.97–1.6 秒段，波形比输入还大；这是非常严重的问题；",
            "**B2**：即使有 AI 降噪，也没能把这段被放大的回声消掉。"],
   subj_en=["Overall none of the four configs is ideal on this clip;",
            "**B1**: far from cancelling the echo, it **amplifies** it - see 0.97-1.6 s, where the output waveform exceeds the input; a severe defect;",
            "**B2**: even with AI denoising, this amplified echo is not removed."],
   verdict_zh=["客观数据把这个发现钉死了：B1/B2 的 FE-ST ERLE 为 **−10.0 / −9.8 dB**——负号意味着输出的回声能量比麦克风输入还高，残余高达 −14 dBFS；A1/A2 为 +27.9 / +25.7 dB。走动导致回声路径时变，基线的线性滤波在此失稳。需要说明：本例 AECMOS 综合分四者接近（回声段很短，被整段平均稀释），但 FE-ST Echo 仍是 B1 最低（3.47），且'回声被放大'属于可闻的硬缺陷。",
              "**判定：A 组胜**——在回声消除的物理量上（ERLE 正负之别）差距是数量级的；A2 对 B2 虽综合分小幅落后（3.85 对 4.13），但 B2 存在可闻的回声放大残余，抑制能力的差距（+25.7 对 −9.8 dB）不是感知分能弥补的。"],
   verdict_en=["The objective data nails the finding: B1/B2's FE-ST ERLE is **-10.0 / -9.8 dB** - the negative sign means the output carries more echo energy than the microphone input, with residuals up to -14 dBFS; A1/A2 measure +27.9 / +25.7 dB. Movement makes the echo path time-varying, and the baseline's linear filter destabilizes. Note that AECMOS composites are close across the four (the echo segments are short and diluted by whole-segment averaging), yet FE-ST Echo is still lowest for B1 (3.47), and audible echo amplification is a hard defect.",
              "**Verdict: group A wins** - on the physical quantity of echo cancellation (positive vs negative ERLE) the gap is an order of magnitude. A2 trails B2 slightly on the composite (3.85 vs 4.13), but B2 carries an audible amplified residual; a suppression gap of +25.7 vs -9.8 dB is not something a perception score can compensate."],
 ),
 4: dict(
   dur=11.02, cmd="--echo 1.6:2.24 --near 9:9.65 --dt 2.25:9,9.66:11.02",
   scenes=dict(echo=[(1.6,2.24)], near=[(9,9.65)], dt=[(2.25,9),(9.66,11.02)]),
   zoom=(1.2,2.8),
   ann=[("b1",1.5,2.3,"试听：明显回声（收敛慢）","Audible clear echo (slow convergence)")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `DNb0qIMRg0iwJqiYFx6RbA_doubletalk` 的 `_mic.wav` 与 `_lpb.wav`。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `DNb0qIMRg0iwJqiYFx6RbA_doubletalk`.",
   title_zh="双讲样本：开头段收敛速度对比", title_en="Double-talk clip: opening-segment convergence",
   subj_zh=["**B1**：1.5–2.3 秒（样本开头的回声段）回声非常明显——**A1 没有这个问题，说明 B1 收敛速度太慢**；",
            "**B2**：借 AI 降噪成功把这段回声消掉了；",
            "其余部分四个配置听感区别不大。"],
   subj_en=["**B1**: very obvious echo at 1.5-2.3 s (the opening echo segment) - **A1 has no such problem, showing B1 converges too slowly**;",
            "**B2**: its AI denoiser successfully removes that echo;",
            "elsewhere the four configs sound about the same."],
   verdict_zh=["听到的开头漏回声在数据里读数明确：B1 的 FE-ST Echo 仅 2.74（四者最低）、ERLE 9.6 dB 对 A1 的 23.0 dB。A2 对 B2 一如既往是风格取舍：B2 抑制更深（ERLE 30.8 对 23.2），A2 综合分与双讲回声分更高（4.03/4.48 对 3.90/4.22）且省 48% 算力。",
              "**判定：A1 对 B1 —— A1 胜**（收敛速度的差距在开头段直接可闻）。**A2 对 B2 —— 各有胜场**，主观区别不大，按算力预算取舍即可。"],
   verdict_en=["The audible opening leak reads clearly in the data: B1's FE-ST Echo is only 2.74 (lowest of the four) with 9.6 dB ERLE vs A1's 23.0 dB. A2 vs B2 is the usual style trade-off: B2 suppresses deeper (ERLE 30.8 vs 23.2), while A2 scores higher on the composite and DT Echo (4.03/4.48 vs 3.90/4.22) and saves 48% compute.",
              "**Verdict: A1 vs B1 - A1 wins** (the convergence gap is directly audible in the opening segment). **A2 vs B2 - split**, subjectively similar; choose by compute budget."],
 ),
 5: dict(
   dur=11.22, cmd="--echo 0:11.22 --no-auto",
   scenes=dict(echo=[(0,11.22)], near=[], dt=[]),
   zoom=(0,11.22),
   ann=[("b1",0.3,10.9,"试听：全程大量残余回声","Audible heavy residual throughout")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `FGqMw1OM4Um5uvmHahuZbg_farend_singletalk` 的 `_mic.wav` 与 `_lpb.wav`。样本只有回声，没有近端与双讲。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `FGqMw1OM4Um5uvmHahuZbg_farend_singletalk`. Echo only - no near-end or double-talk.",
   title_zh="纯回声难样本：残余量级对比", title_en="Echo-only hard clip: residual magnitude comparison",
   subj_zh=["单从波形就能看出差异很大：**B1 几乎全程都是回声**；",
            "**A1** 也有不少残余，但远少于 B1；",
            "**A2、B2** 的 AI 降噪能进一步压低残余，试听感受 **B2 消得更干净**。"],
   subj_en=["The waveforms alone show a large gap: **B1 is nearly all residual echo**;",
            "**A1** also leaves noticeable residual, but far less than B1;",
            "**A2 and B2**'s AI denoisers push the residual further down; by ear **B2 removes it more cleanly**."],
   verdict_zh=["这是一个全员偏难的样本（AECMOS 分数整体偏低）。ERLE 与听感一致：A1 16.0 dB 对 B1 11.6 dB，B2 以 21.6 dB 居首——与'B2 消得更干净'的耳感吻合。一个值得注意的分歧：AECMOS FE-ST Echo 却把 A2 排第一（3.30 对 B2 的 2.72）——在低分段，评分模型对不同残余'风格'的排序可能与人耳不完全一致，这正是我们同时提供主观与客观两条证据链的原因。",
              "**判定：A1 对 B1 —— A1 胜**（ERLE、感知分、听感三者一致）。**A2 对 B2 —— 平手偏各取所需**：B2 抑制深度最佳，A2 感知分最高且只用一半算力。"],
   verdict_en=["A hard clip for everyone (AECMOS scores are low across the board). ERLE matches the ears: A1 16.0 dB vs B1 11.6 dB, with B2 leading at 21.6 dB - consistent with hearing B2 as the cleanest. One notable divergence: AECMOS FE-ST Echo ranks A2 first (3.30 vs B2's 2.72) - in the low-score regime the model's ranking of different residual 'styles' may not fully match human ears, which is exactly why we present both subjective and objective evidence.",
              "**Verdict: A1 vs B1 - A1 wins** (ERLE, perception score and listening all agree). **A2 vs B2 - a draw, pick your priority**: B2 has the deepest suppression; A2 has the highest perception score at half the compute."],
 ),
 6: dict(
   dur=21.69, cmd="--echo 0:21.68 --no-auto",
   scenes=dict(echo=[(0,21.68)], near=[], dt=[]),
   zoom=(8.5,19),
   ann=[("a1",16.8,18.24,"试听：可闻残余","Audible residual"),
        ("b1",16.8,18.24,"同段残余更明显、更响","Same span: louder, clearer residual"),
        ("b1",9.5,9.8,"试听：可闻残余","Audible residual")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `0J0xIs0HJUK2Ex8rHAH2pA_farend_singletalk` 的 `_mic.wav` 与 `_lpb.wav`。样本全部为回声段。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `0J0xIs0HJUK2Ex8rHAH2pA_farend_singletalk`. The entire clip is echo.",
   title_zh="纯回声长样本：残余位置逐点对比", title_en="Long echo-only clip: point-by-point residual comparison",
   subj_zh=["**A1**：16.8–18.24 秒可闻残余回声；",
            "**B1**：同一段残余**更明显、更响**，且 9.5–9.8 秒还多一处可闻残余；",
            "**A2 对 B2**：得益于更好的 AEC 前级，16.8–18.24 秒这段 A2 的表现也优于 B2。"],
   subj_en=["**A1**: audible residual at 16.8-18.24 s;",
            "**B1**: in the same span the residual is **clearer and louder**, with an extra audible residual at 9.5-9.8 s;",
            "**A2 vs B2**: thanks to the better AEC stage, A2 also outperforms B2 in the 16.8-18.24 s span."],
   verdict_zh=["感知分给出了本组测试中最大的分差之一：A1/A2 为 4.01/4.03，B1/B2 仅 2.82/2.99——超过 1 分的差距在 MOS 体系里是'可用'与'勉强'的档位之差。ERLE 同向：A 组在长回声样本上的稳态抑制显著更强。",
              "**判定：A 组双双大幅领先**，同档对比 A1 胜 B1、A2 胜 B2，且都伴随约一半的算力节省。"],
   verdict_en=["The perception scores show one of the largest gaps in this whole suite: A1/A2 at 4.01/4.03 vs B1/B2 at only 2.82/2.99 - a gap of more than one MOS point separates 'usable' from 'barely'. ERLE points the same way: group A's steady-state suppression on a long echo clip is much stronger.",
              "**Verdict: group A leads by a wide margin in both tiers** - A1 beats B1 and A2 beats B2, each at roughly half the compute."],
 ),
 7: dict(
   dur=36.96, cmd="--echo 1.9:11.1 --near 11.2:28 --dt 28:36.95",
   scenes=dict(echo=[(1.9,11.1)], near=[(11.2,28)], dt=[(28,36.95)]),
   zoom=(1.6,3.2),
   ann=[("b1",1.93,2.63,"回声被放大（负 ERLE）","Echo amplified (negative ERLE)"),
        ("b1",28,36.95,"双讲残余（A1/B1 均可闻）","Audible DT residual (both A1/B1)")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `0RUf4sZjqUe862S4gVpZlA_doubletalk_with_movement` 的 `_mic.wav` 与 `_lpb.wav`（带走动的双讲样本，回声电平极低：−39.8 dBFS）。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `0RUf4sZjqUe862S4gVpZlA_doubletalk_with_movement` (double-talk with movement; very low echo level: -39.8 dBFS).",
   title_zh="走动+极低回声电平：又一例基线回声放大", title_en="Movement + very low echo level: another baseline echo-amplification case",
   subj_zh=["**B1**：再次出现严重问题——1.93–2.63 秒回声被**进一步放大**；**B2** 的 AI 降噪也没能把这段消掉；",
            "**A1**：2.65–11.1 秒的回声消除比 B1 更彻底；",
            "**双讲段（28–36.95 秒）**：A1 和 B1 都有很多残余回声——这是对全部配置都困难的一段。"],
   subj_en=["**B1**: the severe problem recurs - the echo at 1.93-2.63 s is **amplified**; **B2**'s AI denoiser also fails to remove it;",
            "**A1**: over 2.65-11.1 s its echo removal is more thorough than B1's;",
            "**Double-talk (28-36.95 s)**: both A1 and B1 leave plenty of residual - a hard span for every config."],
   verdict_zh=["与 case3 同样的机制在此复现：B1/B2 的 FE-ST ERLE 为 **−10.9 / −9.1 dB**（回声被放大），A1/A2 为 +8.7 / +13.0 dB。本例如实呈现两点对 A 组不利的数据：双讲段四者的 DT Echo 都很低（1.84–3.22），B2 借 AI 降噪兜底相对最好（3.22）；综合分也是 B2 最高（3.82）。原因是本例回声电平极低（−39.8 dBFS）且带走动，属于对抑制'风格'极度敏感的边缘样本。",
              "**判定：分裂**——回声消除的物理量上 A 组明确胜出（正 ERLE 对负 ERLE，'放大回声'是硬缺陷）；感知综合分上 B2 领先。这是十个用例中对 A 组最不利的一例，我们照登。"],
   verdict_en=["The same mechanism as case 3 recurs: B1/B2's FE-ST ERLE is **-10.9 / -9.1 dB** (echo amplified) vs A1/A2's +8.7 / +13.0 dB. We also report two data points unfavorable to group A: all four configs score low on DT Echo (1.84-3.22), with B2's AI denoiser providing the best backstop (3.22); B2 also has the highest composite (3.82). The clip's very low echo level (-39.8 dBFS) plus movement makes it an edge case highly sensitive to suppression 'style'.",
              "**Verdict: split** - on the physics of echo cancellation group A clearly wins (positive vs negative ERLE; amplifying echo is a hard defect); on the perceptual composite B2 leads. This is the least favorable of the ten cases for group A, and we publish it as is."],
 ),
 8: dict(
   dur=37.47, cmd="--echo 0:11,30.6:37.4 --near 15.5:27.4 --dt 27.4:30.5",
   scenes=dict(echo=[(0,11),(30.6,37.4)], near=[(15.5,27.4)], dt=[(27.4,30.5)]),
   zoom=(0,11),
   ann=[("b1",0.3,10.7,"试听：明显可闻回声","Audible clear echo")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `mAVjs9dULk24wBwJUyuzcw_doubletalk_with_movement` 的 `_mic.wav` 与 `_lpb.wav`。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `mAVjs9dULk24wBwJUyuzcw_doubletalk_with_movement`.",
   title_zh="双回声段样本：开头段可闻差异", title_en="Two echo segments: an audible gap in the opening span",
   subj_zh=["**B1**：0–11 秒回声段有明显可闻回声，波形差距也很直观；**A1** 在同一段无明显残余；",
            "其他区段听感差别不大；**B2 与 A2** 也区别不大。"],
   subj_en=["**B1**: clearly audible echo across the 0-11 s echo segment, with an equally obvious waveform gap; **A1** shows no clear residual there;",
            "elsewhere the configs sound similar; **B2 and A2** are also close."],
   verdict_zh=["可闻差异落在 FE-ST Echo 上：A1 4.38 对 B1 3.99。本例回声电平较低（−34.9 dBFS），ERLE 绝对值都小（A1 5.1 对 B1 4.8）。如实说明：本例整体差距不大，综合分甚至是 B2 最高（4.45），B1 也有 4.33——十个用例并非每例都是大分差，这正是全量公开的意义。",
              "**判定：A1 对 B1 —— A1 小胜**（唯一可闻差异 + FE 感知分领先）；**A2 对 B2 —— 基本平手**，B2 综合分略高，A2 省 48% 算力。"],
   verdict_en=["The audible gap lands on FE-ST Echo: A1 4.38 vs B1 3.99. The echo level here is low (-34.9 dBFS), so absolute ERLE values are small (A1 5.1 vs B1 4.8). To be candid: the overall gap in this case is modest, and the composite is actually highest for B2 (4.45), with B1 at 4.33 - not every one of the ten cases is a blowout, which is exactly why we publish them all.",
              "**Verdict: A1 vs B1 - a narrow A1 win** (the only audible difference plus the FE perception lead); **A2 vs B2 - essentially a draw**, B2 slightly ahead on composite, A2 saving 48% compute."],
 ),
 9: dict(
   dur=12.76, cmd="--echo 0.62:1.48 --near 2.27:2.91,9.0:9.66 --dt 1.49:2.27,2.92:4.92,5.5:9.0,9.7:12.76",
   scenes=dict(echo=[(0.62,1.48)], near=[(2.27,2.91),(9.0,9.66)], dt=[(1.49,2.27),(2.92,4.92),(5.5,9.0),(9.7,12.76)]),
   zoom=(0.3,1.8),
   ann=[("b1",0.62,1.48,"开头回声未消除","Opening echo not cancelled"),
        ("b1",5.5,9.0,"各双讲段均可闻明显残余","Clear audible residual in every DT segment"),
        ("b2",0.62,1.48,"开头回声仍在","Opening echo still present")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `uL3BLytnwEuieb6jpcG9tQ_doubletalk_with_movement` 的 `_mic.wav` 与 `_lpb.wav`（密集交替双讲）。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `uL3BLytnwEuieb6jpcG9tQ_doubletalk_with_movement` (dense alternating double-talk).",
   title_zh="密集交替双讲：本组差距最大的用例之一", title_en="Dense alternating double-talk: one of the widest gaps in the suite",
   subj_zh=["**开头回声段（0.62–1.48 秒）**：B1 没能消掉，**A1 成功消除**；",
            "**双讲段**：A1 几乎听不到任何残余回声，**B1 在每一个双讲段都能听到明显残余**——本样本 A1 与 B1 的差距非常明显；",
            "**B2**：借 AI 降噪消掉了双讲残余，但开头那段回声同样没消掉；**A2** 没有这些问题。"],
   subj_en=["**Opening echo (0.62-1.48 s)**: B1 fails to cancel it; **A1 removes it cleanly**;",
            "**Double-talk**: A1 leaves almost no audible residual anywhere, while **B1 has clearly audible residual in every DT segment** - the A1-vs-B1 gap on this clip is striking;",
            "**B2**: its AI denoiser cleans up the DT residual but likewise fails on the opening echo; **A2** has none of these problems."],
   verdict_zh=["数据全面呼应听感：FE-ST Echo A1 4.71 对 B1 4.12，DT Echo A1 4.68 对 B1 4.22，成对比较 A1 全项胜。A2 的 ERLE 高达 42.5 dB（残余 −60.4 dBFS），开头段与双讲段双双干净。",
              "**判定：A 组大胜**——A1 对 B1 全项胜且听感差距'非常明显'；A2 对 B2 在抑制深度与双讲回声分上领先（B2 在近端自然度分项略高），伴随 48% 算力节省。"],
   verdict_en=["The data echoes the ears across the board: FE-ST Echo A1 4.71 vs B1 4.12, DT Echo A1 4.68 vs B1 4.22, and A1 wins every row of the paired comparison. A2's ERLE reaches 42.5 dB (residual -60.4 dBFS), clean in both the opening and the DT segments.",
              "**Verdict: a big win for group A** - A1 beats B1 on every row with a subjectively 'striking' gap; A2 leads B2 on suppression depth and DT Echo (B2 slightly ahead on near-end naturalness), with a 48% compute saving."],
 ),
 10: dict(
   dur=10.68, cmd="--echo 0.63:1.96 --near 3.08:3.62,5.16:5.7,7.36:7.91 --dt 1.97:3.07,3.63:5.15,5.7:7.3,7.96:10.68",
   scenes=dict(echo=[(0.63,1.96)], near=[(3.08,3.62),(5.16,5.7),(7.36,7.91)], dt=[(1.97,3.07),(3.63,5.15),(5.7,7.3),(7.96,10.68)]),
   zoom=(3.4,5.6),
   ann=[("b1",0.63,1.96,"回声段轻微残余（波形可见）","Slight residual in echo segment (visible)"),
        ("a1",3.7,5.3,"试听：可闻残余","Audible residual"),
        ("b1",3.7,5.3,"同段残余大得多","Same span: much larger residual")],
   prov_zh="素材取自微软 AEC Challenge 数据集：near/far 分别为 `uNwyJZXU00eLpxsYOkGEFA_doubletalk_with_movement` 的 `_mic.wav` 与 `_lpb.wav`（密集双讲）。",
   prov_en="Material from the Microsoft AEC Challenge dataset: near/far are the `_mic.wav` and `_lpb.wav` of `uNwyJZXU00eLpxsYOkGEFA_doubletalk_with_movement` (dense double-talk).",
   title_zh="密集双讲：基线 FE 感知分崩盘的用例", title_en="Dense double-talk: the case where the baseline's FE perception score collapses",
   subj_zh=["**回声段（0.63–1.96 秒）**：B1 有一点点残余，波形上就能看出来；",
            "**3.7–5.3 秒双讲段**：A1 和 B1 都消不干净这段回声，但从波形看 **B1 的残余大很多**；",
            "同一段里 **B2 的表现却优于 A2**——如实记录。"],
   subj_en=["**Echo segment (0.63-1.96 s)**: B1 leaves a slight residual, visible in the waveform;",
            "**3.7-5.3 s double-talk**: neither A1 nor B1 fully removes the echo, but **B1's residual is much larger** in the waveform;",
            "in that same span **B2 actually outperforms A2** - recorded as heard."],
   verdict_zh=["本例基线的 FE-ST Echo **崩盘**：B1/B2 仅 1.38/1.35，A1/A2 为 4.60/4.58——十个用例中最大的感知分差；ERLE 同向（A 组 53.8/54.3 dB 对 B 组 30.8/36.8 dB）。你听到的 3.7–5.3 秒'B2 局部优于 A2'与整段统计并不矛盾：DT Echo 整段平均仍是 A2 4.01 对 B2 3.79——局部窗口与整段平均可以指向不同方向，这也是主观逐段试听的价值所在。",
              "**判定：A 组大幅领先**（B 组 FE 感知分跌至 1.4 附近属不可用档）；B2 在 3.7–5.3 秒的局部优势与近端自然度分项如实保留在记录中。"],
   verdict_en=["The baseline's FE-ST Echo **collapses** here: B1/B2 score only 1.38/1.35 vs A1/A2's 4.60/4.58 - the largest perception gap of the ten cases; ERLE agrees (group A 53.8/54.3 dB vs group B 30.8/36.8 dB). The 'B2 locally better than A2' heard at 3.7-5.3 s does not contradict the whole-segment statistics: averaged over the DT segments, DT Echo is still A2 4.01 vs B2 3.79 - a local window and a segment average can point different ways, which is precisely the value of segment-by-segment listening.",
              "**Verdict: group A leads by a wide margin** (an FE perception score near 1.4 is in unusable territory); B2's local advantage at 3.7-5.3 s and its near-end naturalness sub-score are kept on the record as heard."],
 ),
}
